// Generated by lsc from index.ts

datatype Option<T> = None | Some(value: T)

datatype NormalizedMappedCIDRMeta = NormalizedMappedCIDRMeta(isIPv4: bool, prefix: int)

datatype IPRestrictionRules = IPRestrictionRules(denyList: Option<seq<IPRestrictionRule>>, allowList: Option<seq<IPRestrictionRule>>)
