// Generated by lsc from matcher.verified.ts

// --- hand-added: Std.Arithmetic for the bit-composition proof (BitOrPow2Split) ---
import opened Std.Arithmetic.DivMod

datatype Option<T> = None | Some(value: T)

function BitAnd(x: int, y: int): int
  requires x >= 0 && y >= 0
  decreases x
{
  if x == 0 || y == 0 then 0
  else 2 * BitAnd(x / 2, y / 2) + (if x % 2 == 1 && y % 2 == 1 then 1 else 0)
}

function BitOr(x: int, y: int): int
  requires x >= 0 && y >= 0
  decreases x
{
  if x == 0 then y
  else if y == 0 then x
  else 2 * BitOr(x / 2, y / 2) + (if x % 2 == 1 || y % 2 == 1 then 1 else 0)
}

// --- hand-added: bit-composition proof kit for mappedIPv6StaticKey ---
// `(0xffff << 32) | ipv4` builds a ::ffff: mapped address by OR-ing a 16-bit
// prefix (bits 32-47) with a 32-bit address (bits 0-31). The two halves have
// disjoint bits, so the OR equals their sum; BitOrPow2Split proves exactly that.
function Pow2(n: nat): int
  ensures Pow2(n) >= 1
{
  if n == 0 then 1 else 2 * Pow2(n - 1)
}

lemma Pow2Double(n: nat)
  ensures Pow2(n + 1) == 2 * Pow2(n)
{
}

lemma Pow2Is32()
  ensures Pow2(32) == 4294967296
{
  Pow2Double(0); Pow2Double(1); Pow2Double(2); Pow2Double(3);
  Pow2Double(4); Pow2Double(5); Pow2Double(6); Pow2Double(7);
  Pow2Double(8); Pow2Double(9); Pow2Double(10); Pow2Double(11);
  Pow2Double(12); Pow2Double(13); Pow2Double(14); Pow2Double(15);
  Pow2Double(16); Pow2Double(17); Pow2Double(18); Pow2Double(19);
  Pow2Double(20); Pow2Double(21); Pow2Double(22); Pow2Double(23);
  Pow2Double(24); Pow2Double(25); Pow2Double(26); Pow2Double(27);
  Pow2Double(28); Pow2Double(29); Pow2Double(30); Pow2Double(31);
}

// high % (2*m) == 0  ==>  high is even and high/2 keeps the divisibility.
lemma ModMul2(high: int, m: int)
  requires m >= 1 && high >= 0 && high % (2 * m) == 0
  ensures high % 2 == 0
  ensures (high / 2) % m == 0
{
  LemmaBreakdown(high, 2, m);
}

// Disjoint bits: if `high` has no bits below position k and `low` fits below k,
// then OR-ing them is the same as adding them.
lemma BitOrPow2Split(high: int, low: int, k: nat)
  requires high >= 0 && low >= 0
  requires high % Pow2(k) == 0
  requires low < Pow2(k)
  ensures BitOr(high, low) == high + low
  decreases k
{
  if k == 0 {
    assert low == 0;
  } else {
    assert Pow2(k) == 2 * Pow2(k - 1);
    ModMul2(high, Pow2(k - 1));
    if high != 0 && low != 0 {
      BitOrPow2Split(high / 2, low / 2, k - 1);
    }
  }
}

datatype CIDRRule = CIDRRule(isIPv4: bool, maskedAddr: int, mask: int)

function isIPv4MappedIPv6(ipv6binary: int): bool
  requires (ipv6binary >= 0)
{
  ((ipv6binary / 4294967296) == 65535)
}

lemma isIPv4MappedIPv6_ensures(ipv6binary: int)
  requires (ipv6binary >= 0)
  ensures (isIPv4MappedIPv6(ipv6binary) == ((ipv6binary / 4294967296) == 65535))
{
}

function convertIPv4MappedIPv6ToIPv4(ipv6binary: int): int
  requires (ipv6binary >= 0)
{
  (ipv6binary % 4294967296)
}

lemma convertIPv4MappedIPv6ToIPv4_ensures(ipv6binary: int)
  requires (ipv6binary >= 0)
  ensures (convertIPv4MappedIPv6ToIPv4(ipv6binary) == (ipv6binary % 4294967296))
  ensures (convertIPv4MappedIPv6ToIPv4(ipv6binary) >= 0)
  ensures (convertIPv4MappedIPv6ToIPv4(ipv6binary) <= 4294967295)
{
}

function resolveIPv4Addr(remoteAddr: int, isIPv4: bool): int
  requires (remoteAddr >= 0)
  requires (isIPv4 ==> (remoteAddr <= 4294967295))
  requires (!(isIPv4) ==> isIPv4MappedIPv6(remoteAddr))
{
  if isIPv4 then
    remoteAddr
  else
    convertIPv4MappedIPv6ToIPv4(remoteAddr)
}

lemma resolveIPv4Addr_ensures(remoteAddr: int, isIPv4: bool)
  requires (remoteAddr >= 0)
  requires (isIPv4 ==> (remoteAddr <= 4294967295))
  requires (!(isIPv4) ==> isIPv4MappedIPv6(remoteAddr))
  ensures (resolveIPv4Addr(remoteAddr, isIPv4) >= 0)
  ensures (resolveIPv4Addr(remoteAddr, isIPv4) <= 4294967295)
{
}

function matchIPv4CIDR(remoteIPv4Addr: int, mask: int, maskedAddr: int): bool
  requires (remoteIPv4Addr >= 0)
  requires (mask >= 0)
  requires (maskedAddr >= 0)
{
  (BitAnd(remoteIPv4Addr, mask) == maskedAddr)
}

function matchSingleCIDR(rule: CIDRRule, remoteAddr: int, remoteIPv4Addr: Option<int>, remoteIsIPv4: bool): bool
  requires (remoteAddr >= 0)
  requires (match remoteIPv4Addr { case Some(i_remoteIPv4Addr_val) => (i_remoteIPv4Addr_val >= 0) case None => true })
  requires (rule.mask >= 0)
  requires (rule.maskedAddr >= 0)
{
  if rule.isIPv4 then
    match remoteIPv4Addr {
      case Some(i_remoteIPv4Addr_val) =>
        matchIPv4CIDR(i_remoteIPv4Addr_val, rule.mask, rule.maskedAddr)
      case None =>
        false
    }
  else
    if remoteIsIPv4 then
      false
    else
      (BitAnd(remoteAddr, rule.mask) == rule.maskedAddr)
}

function matcherCIDREquivalence(rule: CIDRRule, ipv4Addr: int): bool
  requires rule.isIPv4
  requires (rule.mask >= 0)
  requires (rule.maskedAddr >= 0)
  requires (ipv4Addr >= 0)
  requires (ipv4Addr <= 4294967295)
{
  matchSingleCIDR(rule, ipv4Addr, Some(resolveIPv4Addr(ipv4Addr, true)), true)
}

lemma matcherCIDREquivalence_ensures(rule: CIDRRule, ipv4Addr: int)
  requires rule.isIPv4
  requires (rule.mask >= 0)
  requires (rule.maskedAddr >= 0)
  requires (ipv4Addr >= 0)
  requires (ipv4Addr <= 4294967295)
  ensures (matcherCIDREquivalence(rule, ipv4Addr) == matchSingleCIDR(rule, (MAPPED_PREFIX + ipv4Addr), Some(resolveIPv4Addr((MAPPED_PREFIX + ipv4Addr), false)), false))
{
}

function mappedIPv6StaticKey(ipv4binary: int): int
  requires (ipv4binary >= 0)
  requires (ipv4binary <= 4294967295)
{
  BitOr((65535 * 4294967296), ipv4binary)
}

lemma mappedIPv6StaticKey_ensures(ipv4binary: int)
  requires (ipv4binary >= 0)
  requires (ipv4binary <= 4294967295)
  ensures (mappedIPv6StaticKey(ipv4binary) == (MAPPED_PREFIX + ipv4binary))
  ensures (mappedIPv6StaticKey(ipv4binary) >= 0)
  ensures isIPv4MappedIPv6(mappedIPv6StaticKey(ipv4binary))
  ensures (convertIPv4MappedIPv6ToIPv4(mappedIPv6StaticKey(ipv4binary)) == ipv4binary)
{
  Pow2Is32();
  BitOrPow2Split(65535 * 4294967296, ipv4binary, 32);
}

const MAPPED_PREFIX: int := 281470681743360
