// Generated by lsc from matcher.verified.ts

datatype Option<T> = None | Some(value: T)

function BitAnd(x: int, y: int): int
  requires x >= 0 && y >= 0
  decreases x
{
  if x == 0 || y == 0 then 0
  else 2 * BitAnd(x / 2, y / 2) + (if x % 2 == 1 && y % 2 == 1 then 1 else 0)
}

datatype CIDRRule = CIDRRule(isIPv4: bool, maskedAddr: int, mask: int)

function isIPv4MappedIPv6(ipv6binary: int): bool
  requires (ipv6binary >= 0)
{
  ((ipv6binary / 4294967296) == 65535)
}

lemma isIPv4MappedIPv6_ensures(ipv6binary: int)
  requires (ipv6binary >= 0)
  ensures (isIPv4MappedIPv6(ipv6binary) == ((ipv6binary / 4294967296) == 65535))
{
}

function convertIPv4MappedIPv6ToIPv4(ipv6binary: int): int
  requires (ipv6binary >= 0)
{
  (ipv6binary % 4294967296)
}

lemma convertIPv4MappedIPv6ToIPv4_ensures(ipv6binary: int)
  requires (ipv6binary >= 0)
  ensures (convertIPv4MappedIPv6ToIPv4(ipv6binary) == (ipv6binary % 4294967296))
  ensures (convertIPv4MappedIPv6ToIPv4(ipv6binary) >= 0)
  ensures (convertIPv4MappedIPv6ToIPv4(ipv6binary) <= 4294967295)
{
}

function resolveIPv4Addr(remoteAddr: int, isIPv4: bool): int
  requires (remoteAddr >= 0)
  requires (isIPv4 ==> (remoteAddr <= 4294967295))
  requires (!(isIPv4) ==> isIPv4MappedIPv6(remoteAddr))
{
  if isIPv4 then
    remoteAddr
  else
    convertIPv4MappedIPv6ToIPv4(remoteAddr)
}

lemma resolveIPv4Addr_ensures(remoteAddr: int, isIPv4: bool)
  requires (remoteAddr >= 0)
  requires (isIPv4 ==> (remoteAddr <= 4294967295))
  requires (!(isIPv4) ==> isIPv4MappedIPv6(remoteAddr))
  ensures (resolveIPv4Addr(remoteAddr, isIPv4) >= 0)
  ensures (resolveIPv4Addr(remoteAddr, isIPv4) <= 4294967295)
{
}

function matchIPv4CIDR(remoteIPv4Addr: int, mask: int, maskedAddr: int): bool
  requires (remoteIPv4Addr >= 0)
  requires (mask >= 0)
  requires (maskedAddr >= 0)
{
  (BitAnd(remoteIPv4Addr, mask) == maskedAddr)
}

function matchSingleCIDR(rule: CIDRRule, remoteAddr: int, remoteIPv4Addr: Option<int>, remoteIsIPv4: bool): bool
  requires (remoteAddr >= 0)
  requires (match remoteIPv4Addr { case Some(i_remoteIPv4Addr_val) => (i_remoteIPv4Addr_val >= 0) case None => true })
  requires (rule.mask >= 0)
  requires (rule.maskedAddr >= 0)
{
  if rule.isIPv4 then
    match remoteIPv4Addr {
      case Some(i_remoteIPv4Addr_val) =>
        matchIPv4CIDR(i_remoteIPv4Addr_val, rule.mask, rule.maskedAddr)
      case None =>
        false
    }
  else
    if remoteIsIPv4 then
      false
    else
      (BitAnd(remoteAddr, rule.mask) == rule.maskedAddr)
}

function matcherCIDREquivalence(rule: CIDRRule, ipv4Addr: int): bool
  requires rule.isIPv4
  requires (rule.mask >= 0)
  requires (rule.maskedAddr >= 0)
  requires (ipv4Addr >= 0)
  requires (ipv4Addr <= 4294967295)
{
  matchSingleCIDR(rule, ipv4Addr, Some(resolveIPv4Addr(ipv4Addr, true)), true)
}

lemma matcherCIDREquivalence_ensures(rule: CIDRRule, ipv4Addr: int)
  requires rule.isIPv4
  requires (rule.mask >= 0)
  requires (rule.maskedAddr >= 0)
  requires (ipv4Addr >= 0)
  requires (ipv4Addr <= 4294967295)
  ensures (matcherCIDREquivalence(rule, ipv4Addr) == matchSingleCIDR(rule, (MAPPED_PREFIX + ipv4Addr), Some(resolveIPv4Addr((MAPPED_PREFIX + ipv4Addr), false)), false))
{
}

const MAPPED_PREFIX: int := 281470681743360
