// Generated by lsc from verified.ts

datatype AddressType = IPv4 | IPv6

datatype NormalizedMappedCIDRMeta = NormalizedMappedCIDRMeta(isIPv4: bool, prefix: int)

function normalizeMappedCIDRMeta(type_: AddressType, prefix: int, isMappedIPv6: bool): NormalizedMappedCIDRMeta
  requires (type_.IPv4? ==> ((prefix >= 0) && (prefix <= 32)))
  requires (type_.IPv6? ==> ((prefix >= 0) && (prefix <= 128)))
{
  if type_.IPv4? then
    NormalizedMappedCIDRMeta(true, prefix)
  else
    if (isMappedIPv6 && (prefix >= 96)) then
      NormalizedMappedCIDRMeta(true, (prefix - 96))
    else
      NormalizedMappedCIDRMeta(false, prefix)
}

lemma normalizeMappedCIDRMeta_ensures(type_: AddressType, prefix: int, isMappedIPv6: bool)
  requires (type_.IPv4? ==> ((prefix >= 0) && (prefix <= 32)))
  requires (type_.IPv6? ==> ((prefix >= 0) && (prefix <= 128)))
  ensures (type_.IPv4? ==> (normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).isIPv4 == true))
  ensures (type_.IPv4? ==> (normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).prefix == prefix))
  ensures (type_.IPv6? ==> !((isMappedIPv6 && (prefix >= 96))) ==> (normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).isIPv4 == false))
  ensures (type_.IPv6? ==> !((isMappedIPv6 && (prefix >= 96))) ==> (normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).prefix == prefix))
  ensures (type_.IPv6? ==> isMappedIPv6 ==> (prefix >= 96) ==> (normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).isIPv4 == true))
  ensures (type_.IPv6? ==> isMappedIPv6 ==> (prefix >= 96) ==> (normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).prefix == (prefix - 96)))
  ensures (normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).isIPv4 ==> ((normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).prefix >= 0) && (normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).prefix <= 32)))
  ensures (!(normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).isIPv4) ==> ((normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).prefix >= 0) && (normalizeMappedCIDRMeta(type_, prefix, isMappedIPv6).prefix <= 128)))
{
}

function ipv4StaticRuleAliases(rule: string): seq<string>
{
  [rule, ("::ffff:" + rule)]
}

lemma ipv4StaticRuleAliases_ensures(rule: string)
  ensures (|ipv4StaticRuleAliases(rule)| == 2)
  ensures (ipv4StaticRuleAliases(rule)[0] == rule)
  ensures (ipv4StaticRuleAliases(rule)[1] == ("::ffff:" + rule))
{
}

method addIPv4StaticRule(rules: set<string>, rule: string) returns (res: set<string>)
  ensures (rule in res)
  ensures (("::ffff:" + rule) in res)
{
  var rules := rules;
  var i_t0 := ipv4StaticRuleAliases(rule);
  var aliases := i_t0;
  rules := (rules + {aliases[0]});
  rules := (rules + {aliases[1]});
  return rules;
}
