// Generated by lsc from cookie.ts

datatype SecureCookieConstraint = SecureCookieConstraint(secure: bool)

datatype HostCookieConstraint = HostCookieConstraint(secure: bool, path: string, domain: ())

datatype CookiePrefixOptions = host | secure

method trimCookieWhitespace(value: string) returns (res: string)
  ensures (|res| <= |value|)
{
  var start := 0;
  var end := |value|;
  while (start < end)
    invariant (start >= 0)
    invariant (start <= end)
    invariant (end <= |value|)
  {
    var charCode := (value[start] as int);
    if ((charCode != 32) && (charCode != 9)) {
      break;
    }
    start := (start + 1);
  }
  while (end > start)
    invariant (start >= 0)
    invariant (start <= end)
    invariant (end <= |value|)
  {
    var charCode := (value[(end - 1)] as int);
    if ((charCode != 32) && (charCode != 9)) {
      break;
    }
    end := (end - 1);
  }
  return if ((start == 0) && (end == |value|)) then value else value[start..end];
}
