// Generated by lsc from ipaddr.verified.ts

function isIPv4MappedIPv6(ipv6binary: int): bool
  requires (ipv6binary >= 0)
{
  ((ipv6binary / 4294967296) == 65535)
}

lemma isIPv4MappedIPv6_ensures(ipv6binary: int)
  requires (ipv6binary >= 0)
  ensures (isIPv4MappedIPv6(ipv6binary) == ((ipv6binary / 4294967296) == 65535))
{
}

function convertIPv4MappedIPv6ToIPv4(ipv6binary: int): int
  requires (ipv6binary >= 0)
{
  (ipv6binary % 4294967296)
}

lemma convertIPv4MappedIPv6ToIPv4_ensures(ipv6binary: int)
  requires (ipv6binary >= 0)
  ensures (convertIPv4MappedIPv6ToIPv4(ipv6binary) == (ipv6binary % 4294967296))
  ensures (convertIPv4MappedIPv6ToIPv4(ipv6binary) >= 0)
  ensures (convertIPv4MappedIPv6ToIPv4(ipv6binary) <= 4294967295)
{
}
